config/routes.rb
Rails.application.routes.draw do
  resources :games
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pearls
  devise_for :users
	
	root 'pearls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :pearls

  validates :title, :description, presence: true
end

app/models/pearl.rb
class Pearl < ApplicationRecord
  belongs_to :user
  belongs_to :game
  
  validates :quote, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :pearls
  has_many :games
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	protected
	
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :set_users, only: [:new, :create, :edit, :update]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    def set_users
      @users = User.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :description, :master, :user_id)
    end
end

app/controllers/pearls_controller.rb
class PearlsController < ApplicationController
  before_action :set_pearl, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :set_users, only: [:new, :create, :edit, :update]
  before_action :set_games, only: [:new, :create, :edit, :update]

  # GET /pearls
  # GET /pearls.json
  def index
    @pearls = Pearl.all
  end

  # GET /pearls/1
  # GET /pearls/1.json
  def show
  end

  # GET /pearls/new
  def new
    @pearl = Pearl.new
  end

  # GET /pearls/1/edit
  def edit
  end

  # POST /pearls
  # POST /pearls.json
  def create
    @pearl = Pearl.new(pearl_params)

    respond_to do |format|
      if @pearl.save
        format.html { redirect_to @pearl, notice: 'Pearl was successfully created.' }
        format.json { render :show, status: :created, location: @pearl }
      else
        format.html { render :new }
        format.json { render json: @pearl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pearls/1
  # PATCH/PUT /pearls/1.json
  def update
    respond_to do |format|
      if @pearl.update(pearl_params)
        format.html { redirect_to @pearl, notice: 'Pearl was successfully updated.' }
        format.json { render :show, status: :ok, location: @pearl }
      else
        format.html { render :edit }
        format.json { render json: @pearl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pearls/1
  # DELETE /pearls/1.json
  def destroy
    @pearl.destroy
    respond_to do |format|
      format.html { redirect_to pearls_url, notice: 'Pearl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pearl
      @pearl = Pearl.find(params[:id])
    end
  
    def set_users
      @users = User.all
    end
  
    def set_games
      @games = Game.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pearl_params
      params.require(:pearl).permit(:quote, :game_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pearls_helper.rb
module PearlsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, @users.map { |user| [user.name, user.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.description %></td>
        <td><%= game.user.name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @game.user.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mediocres</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if !user_signed_in? %>
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Signup', new_user_registration_path %>
    <% else %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <%= link_to 'Edit', edit_user_registration_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pearls/_form.html.erb
<%= form_with(model: pearl, local: true) do |form| %>
  <% if pearl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pearl.errors.count, "error") %> prohibited this pearl from being saved:</h2>

      <ul>
      <% pearl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quote %>
    <%= form.text_area :quote %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.select :game_id, @games.map { |game| [game.title, game.id] } %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select :user_id, @users.map { |user| [user.name, user.id] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pearls/edit.html.erb
<h1>Editing Pearl</h1>

<%= render 'form', pearl: @pearl %>

<%= link_to 'Show', @pearl %> |
<%= link_to 'Back', pearls_path %>

app/views/pearls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pearls</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pearls.each do |pearl| %>
      <tr>
        <td><%= pearl.quote %></td>
        <td><%= pearl.user.name %></td>
        <td><%= link_to 'Show', pearl %></td>
        <td><%= link_to 'Edit', edit_pearl_path(pearl) %></td>
        <td><%= link_to 'Destroy', pearl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pearl', new_pearl_path %>

app/views/pearls/new.html.erb
<h1>New Pearl</h1>

<%= render 'form', pearl: @pearl %>

<%= link_to 'Back', pearls_path %>

app/views/pearls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @pearl.quote %>
</p>

<p>
  <strong>User:</strong>
  <%= @pearl.game.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @pearl.user.name %>
</p>

<%= link_to 'Edit', edit_pearl_path(@pearl) %> |
<%= link_to 'Back', pearls_path %>